const actionTypes = {
  USER_INFO: 'USER_INFO', 
  USER_INFO_Access_token: 'USER_INFO_Access_token', 

  USER_INFO_Access_token_signup: 'USER_INFO_Access_token_signup', 
  START_LOADING: 'START_LOADING', 
  CLOSE_LOADING: 'CLOSE_LOADING', 
  TESTIMONIALS: 'TESTIMONIALS', 
  UPDATE_PROFILE: 'UPDATE_PROFILE', 
  LOG_OUT: 'LOG_OUT', 
  MY_SUBSCRIPTION: 'MY_SUBSCRIPTION',
  MONTHLY_GRAPH_DATA: 'MONTHLY_GRAPH_DATA',
  SHIPMENT_BUYER_WISE: 'SHIPMENT_BUYER_WISE',
  TABLE_GRAPH_DATA: 'TABLE_GRAPH_DATA',
  MADE_UP_GRAPH: 'MADE_UP_GRAPH',
  GRAY_FABRICS: 'GRAY_FABRICS',
  ABOUT_US: 'ABOUT_US',
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  PAYMENT_LOGS: 'PAYMENT_LOGS',
  USER_STREAM: 'USER_STREAM',
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  GET_EMPLOYEES_EMAILS: 'GET_EMPLOYEES_EMAILS',
  STOCK_IN_HAND: 'STOCK_IN_HAND',
  DECREMENT: 'DECREMENT',
  ORDER_PLACED: 'ORDER_PLACED',

  CATEGORIES: 'CATEGORIES',
  HIDE_SEARCH: 'HIDE_SEARCH',
  SHOW_SEARCH: 'SHOW_SEARCH',
  WISHLIST: 'WISHLIST',
};

export default actionTypes;
